package record

import (
	"bytes"
	"reflect"
	"strings"
	"testing"
)

// manualReferenceCast is a strictly hand-written reference according to asciinema v2 specification.
// It is NOT generated by any code.
const manualReferenceCast = `{"version":2,"width":80,"height":24,"timestamp":1700000000,"env":{"TERM":"xterm-256color"}}
[0,"o","Welcome to iamtunnel\r\n"]
[0.15,"o","machine-01 login: "]
[0.5,"o","admin\r\n"]
[0.75,"o","Password: "]
[1.2,"o","\r\nLast login: Tue Nov 14 22:00:00 on pts/0\r\n"]
[1.5,"o","admin@machine-01:~$ "]
[2,"o","uname -a\r\n"]
[2.25,"o","Linux machine-01 6.5.0 #1 SMP x86_64\r\n"]
[2.8,"o","admin@machine-01:~$ "]
[3.1,"r","120x35"]
[3.5,"o","exit\r\n"]
[3.9,"o","logout\r\n"]
`

func TestCastHeaderAndEventsManualReference(t *testing.T) {
	var buf bytes.Buffer
	cw := NewCastWriter(&buf)

	header := CastHeader{
		Version:   2,
		Width:     80,
		Height:    24,
		Timestamp: 1700000000,
		Env: map[string]string{
			"TERM": "xterm-256color",
		},
	}

	if err := cw.WriteHeader(header); err != nil {
		t.Fatalf("WriteHeader failed: %v", err)
	}

	events := []struct {
		t float64
		e string
		d string
	}{
		{0.0, "o", "Welcome to iamtunnel\r\n"},
		{0.15, "o", "machine-01 login: "},
		{0.5, "o", "admin\r\n"},
		{0.75, "o", "Password: "},
		{1.2, "o", "\r\nLast login: Tue Nov 14 22:00:00 on pts/0\r\n"},
		{1.5, "o", "admin@machine-01:~$ "},
		{2.0, "o", "uname -a\r\n"},
		{2.25, "o", "Linux machine-01 6.5.0 #1 SMP x86_64\r\n"},
		{2.8, "o", "admin@machine-01:~$ "},
		{3.1, "r", "120x35"},
		{3.5, "o", "exit\r\n"},
		{3.9, "o", "logout\r\n"},
	}

	for i, ev := range events {
		var err error
		switch ev.e {
		case "o":
			err = cw.WriteOutput(ev.t, []byte(ev.d))
		case "r":
			err = cw.WriteEvent(ev.t, "r", ev.d)
		default:
			err = cw.WriteEvent(ev.t, ev.e, ev.d)
		}
		if err != nil {
			t.Fatalf("event %d failed: %v", i, err)
		}
	}

	actual := buf.String()
	if actual != manualReferenceCast {
		t.Fatalf("generated .cast does not match hand-written reference.\nExpected:\n%s\nGot:\n%s", manualReferenceCast, actual)
	}

	// Also verify each line individually against manual reference
	expectedLines := strings.Split(strings.TrimRight(manualReferenceCast, "\n"), "\n")
	actualLines := strings.Split(strings.TrimRight(actual, "\n"), "\n")

	if len(actualLines) != len(expectedLines) {
		t.Fatalf("line count mismatch: expected %d, got %d", len(expectedLines), len(actualLines))
	}

	for i := range expectedLines {
		if actualLines[i] != expectedLines[i] {
			t.Errorf("line %d mismatch:\nexpected: %s\ngot:      %s", i+1, expectedLines[i], actualLines[i])
		}
	}
}

func TestCastResizeEvent(t *testing.T) {
	var buf bytes.Buffer
	cw := NewCastWriter(&buf)

	if err := cw.WriteResize(4.5, 100, 30); err != nil {
		t.Fatalf("WriteResize failed: %v", err)
	}

	expected := "[4.5,\"r\",\"100x30\"]\n"
	if buf.String() != expected {
		t.Fatalf("expected %q, got %q", expected, buf.String())
	}
}

// TestIncomingStreamRecordingProhibited enforces SPEC §6.5: incoming stream (stdin/'i')
// must NEVER be recorded so passwords typed at a shell never reach recordings.
// This test actively verifies that:
// 1. Neither Recorder nor CastWriter export a WriteInput method.
// 2. CastWriter.WriteEvent explicitly rejects 'i' events with an error.
func TestIncomingStreamRecordingProhibited(t *testing.T) {
	// 1. Verify CastWriter does not export WriteInput
	cwType := reflect.TypeOf((*CastWriter)(nil))
	if _, ok := cwType.MethodByName("WriteInput"); ok {
		t.Fatalf("SECURITY VIOLATION: CastWriter exports WriteInput! Incoming stream recording is prohibited by SPEC §6.5")
	}

	// 2. Verify Recorder does not export WriteInput
	recType := reflect.TypeOf((*Recorder)(nil))
	if _, ok := recType.MethodByName("WriteInput"); ok {
		t.Fatalf("SECURITY VIOLATION: Recorder exports WriteInput! Incoming stream recording is prohibited by SPEC §6.5")
	}

	// 3. Verify WriteEvent with "i" is rejected
	var buf bytes.Buffer
	cw := NewCastWriter(&buf)
	err := cw.WriteEvent(1.25, "i", "SecretPassword123\n")
	if err == nil {
		t.Fatalf("expected WriteEvent('i') to return error, got nil")
	}
	if buf.Len() != 0 {
		t.Fatalf("buffer must remain empty when 'i' event is rejected, got %q", buf.String())
	}
}

func TestCastSpecialCharacterEscaping(t *testing.T) {
	var buf bytes.Buffer
	cw := NewCastWriter(&buf)

	// String containing quotes, backslashes, tabs, newlines, and ANSI escape codes
	payload := "Path: \"C:\\Windows\\System32\"\t\x1b[31mRed\x1b[0m\r\n"
	if err := cw.WriteOutput(0.5, []byte(payload)); err != nil {
		t.Fatalf("WriteOutput failed: %v", err)
	}

	out := buf.String()
	if !strings.Contains(out, "\\\"C:\\\\Windows\\\\System32\\\"") {
		t.Errorf("path quotes or backslashes not properly JSON escaped: %s", out)
	}
	if !strings.Contains(out, "\\u001b[31mRed\\u001b[0m") {
		t.Errorf("ANSI escape not properly JSON escaped: %s", out)
	}
}
